#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [1]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [2]:
A = np.array([[1,1,1],[2,2,3],[3,3,3]])
A
np.shape(A)[1]
def SymCheck(A):
    m = np.shape(A)[0]
    n = np.shape(A)[1]
    i = 0
    a = 0
    while i < m:
        j = 0
        while j < n:
            if A[i,j] == A[j,i]:
                j += 1
            else:
                a = 1
                break
            
        i+=1
    if a == 0:
        print("Symmetric")
    else:
        print("Non-Symmetric")
    

Test your function on the two matrices below

In [3]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [4]:
SymCheck(A)

Non-Symmetric


In [5]:
SymCheck(SymMatrix)

Symmetric


## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library (`np.zeroes`, `np.ones`, `np.shape`, etc are all ok to use).

In [6]:
def Transpose(A):
    n = np.shape(A)[0]
    AT = np.zeros((n,n))
    i=0
    while i < n:
        j=0
        while j < n:
            AT[i,j] = A[j,i]
            j += 1
        i += 1
    return AT

Check your code by transposing a matrix by checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [7]:
A = np.random.rand(6,6);
A == Transpose(A)

#As all entries are not true the matrices are not equal so the statement is verified

array([[ True, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False,  True, False],
       [False, False, False, False, False,  True]])

In [8]:
AT = Transpose(A)
Transpose(AT)-A
#the zero matrix, so the statement is verified

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [8]:
def MatrixMax(A):
    m = np.shape(A)[0]
    n = np.shape(A)[1]
    i = 0
    a = A[0,0]
    while i < m:
        j = 0
        while j < n:
            if A[i,j] > a:
                a = A[i,j]
            j += 1
        i += 1
    return (a)
            

Check your result by comparing to `np.max(A)` for the below random matrix

In [9]:
A = np.random.rand(4,5)

MatrixMax(A)-np.max(A)

0.0

Commit your notebook to git and push it to GitHub.

# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()` (`np.shape`, `np.inf`, etc are ok to use).

In [10]:
def Norm1(A):
    m = np.shape(A)[0]
    n = np.shape(A)[1]
    j=0
    a=0
    while j < n:
        i = 0
        a1 = 0
        while i < m:
            a1 += np.abs(A[i,j])
            i += 1
        if a1 > a:
            a = a1
        j += 1
    return a

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [11]:
A = np.random.rand(3,4)
Norm1(A)-la.norm(A,1)

0.0

## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [12]:
def NormInf(A):
    m = np.shape(A)[0]
    n = np.shape(A)[1]
    i=0
    a=0
    while i < m:
        j = 0
        a1 = 0
        while j < n:
            a1 += np.abs(A[i,j])
            j += 1
        if a1 > a:
            a = a1
        i += 1
    return a

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [13]:
A = np.random.rand(3,4)
NormInf(A)-la.norm(A,np.inf)


0.0

Commit your notebook to git and push it to GitHub.

# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [14]:
A1 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A2 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

In [15]:
def ConditionNo(A):
    eig = la.eig(A.T@A)[0]
    lmax = np.max(eig)
    lmin = np.min(eig)
    k = np.sqrt(lmax/lmin)
    return k
print(ConditionNo(A1))
print(ConditionNo(A2))
print(ConditionNo(A3))
#A1 is ill-conditioned as it has a very large condition no

150627876.18055668
21.552466488381775
15.122449699410613


# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A1$ and $A2$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{1,2\}$.

In [16]:
db = np.array([0.1,0,0,0])
b = np.array([1,2,3,4])
PercentB = 100*la.norm(db,2)/la.norm(b,2)
print("percent change in b = " +str(PercentB))

x1=la.inv(A1)@b
dx1 = la.inv(A1)@(b+db)-x1
PercentX1 = 100*la.norm(dx1,2)/la.norm(x1,2)
print("Percent change in x1 = "+str(PercentX1))

percent change in b = 1.8257418583505538
Percent change in x1 = 512.6206098890646


In [17]:
x2=la.inv(A2)@b
dx2 = la.inv(A2)@(b+db)-x2
PercentX2 = 100*la.norm(dx2,2)/la.norm(x2,2)
print("Percent change in x2 = "+str(PercentX2))

Percent change in x2 = 10.483582220339118


Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [18]:
# Answer here
#A1. This could be guessed from the large condition number

Commit your notebook to git and push it to GitHub.

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [19]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

In [20]:
Eigenvalues, Eigenvectors=la.eig(A)
Eigenvalues, Eigenvectors

(array([15.78569318, -2.05164645,  1.26595327]),
 array([[-0.39252008, -0.89589878,  0.09818766],
        [-0.44424151,  0.36255198, -0.77454142],
        [-0.80534308,  0.25675168,  0.6248558 ]]))

In [29]:
EVals = sorted(la.eig(A)[0], reverse = True)

In [30]:
for i in range(0,3):
    print(EVals[i])


15.785693179172181
1.2659532728352205
-2.051646452007405


In [53]:
np.dot(A,Eigenvectors[:,0]) - Eigenvalues[0]*Eigenvectors[:,0]

array([-2.66453526e-15, -1.77635684e-15,  0.00000000e+00])

In [54]:
np.dot(A,Eigenvectors[:,1]) - Eigenvalues[1]*Eigenvectors[:,1]

array([-2.22044605e-16,  3.33066907e-16, -1.11022302e-16])

In [55]:
np.dot(A,Eigenvectors[:,2]) - Eigenvalues[2]*Eigenvectors[:,2]
#these values are approx 0, so the statement is verified

array([-1.24900090e-16, -2.22044605e-16,  9.99200722e-16])

# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [64]:
A = np.array([[2.65287619, 1.58615494, 1.47170961, 1.40586081],
       [1.58615494, 1.17577323, 0.72084593, 0.79382861],
       [1.47170961, 0.72084593, 1.18111969, 0.6654689 ],
       [1.40586081, 0.79382861, 0.6654689 , 0.84502394]])

In [31]:
def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("Matrix must be square")
        return
    
    # Create a random initial vector
    x = np.random.rand(m)
    
    lam = 0.1
    lamprev = 1
    while np.abs(1-lam/lamprev) > err:
        Ax      = A@x
        lamprev = lam
        lam = la.norm(Ax,2)/la.norm(x,2)
        x = Ax
        
    x = x/la.norm(x)
    return (lam,x)



eig1 = MaxEigenvalue(A, 1e-10)
eig4 = 1/MaxEigenvalue(la.inv(A), 1e-5)[0], -MaxEigenvalue(la.inv(A), 1e-5)[1]

l1 = eig1[0]
e1 = eig1[1]

B1 = A - l1*np.outer(e1, e1)
eig2 = MaxEigenvalue(B1, 1e-10)

l2 = eig2[0]
e2 = eig2[1]

B2 = B1 - l2*np.outer(e2, e2)
eig3 = MaxEigenvalue(B2, 1e-10)

In [32]:
print(eig1)
print(eig2)
print(eig3)
print(eig4)

(15.785693179370094, array([0.39252008, 0.44424151, 0.80534308]))
(2.0516464521399493, array([ 0.83890032, -0.41382256, -0.35354933]))
(4.10329290431264, array([ 0.83890032, -0.41382256, -0.35354933]))
(1.2659577108282452, array([ 0.0981929 , -0.77454262,  0.62485349]))


Check your answers against Numpy's results from `la.eig(A)`

In [33]:
la.eig(A)

(array([15.78569318, -2.05164645,  1.26595327]),
 array([[-0.39252008, -0.89589878,  0.09818766],
        [-0.44424151,  0.36255198, -0.77454142],
        [-0.80534308,  0.25675168,  0.6248558 ]]))

Commit your notebook to git and push it to GitHub. Upload your completed assignment to BrightSpace.